This is Makefile.info, produced by makeinfo version 5.2 from Makefile.

# makefile: lets try objects = main_3d.o mpi_3d.o initialise_3d.o
exchng3.o fnd3dnbrs.o mpe_decomp1d.o pressure.o vel_coeff3d.o
vel_cap3d.o umome_3d.o vmome_3d.o wmome_3d.o mass_3d.o pressure_cor.o
uvw_vel.o species_coeff.o species_calc.o tridag.o screen.o duvwdt.o

   Comp = /usr/bin/mpif90

   FFLAGS = -O3

   main_3d : $(objects)	$(Comp) -o main_3d$(objects)

   %.o : %.f90	$(Comp) -c$<


Tag Table:

End Tag Table
